// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC0L0pCDwSFIRqT4mxzK77kpieLfnFqqs',
    appId: '1:915831626660:web:7e99f2f9c2bd326db6bf31',
    messagingSenderId: '915831626660',
    projectId: 'registration-backend-f2f6b',
    authDomain: 'registration-backend-f2f6b.firebaseapp.com',
    storageBucket: 'registration-backend-f2f6b.firebasestorage.app',
    measurementId: 'G-31WEBY00PF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCw8tWezwkI8y3MN6-wDrDFonvyYWBhpU',
    appId: '1:915831626660:android:0972ac8fd22ee88ab6bf31',
    messagingSenderId: '915831626660',
    projectId: 'registration-backend-f2f6b',
    storageBucket: 'registration-backend-f2f6b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEOE2D41bwY_-zsXF11Y9da3TDCa9QYIk',
    appId: '1:915831626660:ios:5996021e04ddc24fb6bf31',
    messagingSenderId: '915831626660',
    projectId: 'registration-backend-f2f6b',
    storageBucket: 'registration-backend-f2f6b.firebasestorage.app',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEOE2D41bwY_-zsXF11Y9da3TDCa9QYIk',
    appId: '1:915831626660:ios:5996021e04ddc24fb6bf31',
    messagingSenderId: '915831626660',
    projectId: 'registration-backend-f2f6b',
    storageBucket: 'registration-backend-f2f6b.firebasestorage.app',
    iosBundleId: 'com.example.loginpage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC0L0pCDwSFIRqT4mxzK77kpieLfnFqqs',
    appId: '1:915831626660:web:292ad6c2cc9ea49ab6bf31',
    messagingSenderId: '915831626660',
    projectId: 'registration-backend-f2f6b',
    authDomain: 'registration-backend-f2f6b.firebaseapp.com',
    storageBucket: 'registration-backend-f2f6b.firebasestorage.app',
    measurementId: 'G-MLYPLWNMF9',
  );
}
